// Code generated by file2byteslice. DO NOT EDIT.

package shaders

var Hollow = []byte("// Copyright (c) 2022 Anıl Konaç\n// This file is licensed under the MIT license.\n\n//go:build ignore\n\npackage main\n\nvar Color vec4\nvar Thickness float\nvar Width float\nvar Height float\n\nfunc Fragment(position vec4, texCoord vec2, color vec4) vec4 {\n\tnormColor := Color / 0xffff\n\n\trealX := Width * texCoord.x\n\trealY := Height * texCoord.y\n\tif (realX >= Thickness) && (realX <= Width-Thickness) &&\n\t\t(realY >= Thickness) && (realY <= Height-Thickness) {\n\t\tnormColor.a = 0\n\t}\n\n\tnormColor.xyz *= normColor.a\n\treturn normColor\n}\n")
