// Code generated by file2byteslice. DO NOT EDIT.

package shaders

var Hollow = []byte("//go:build ignore\r\n\r\npackage main\r\n\r\nvar Color vec4\r\nvar RectSize vec2\r\nvar RectPosInUnit vec2\r\nvar TotalSize vec2\r\nvar Thickness float\r\n\r\nfunc Fragment(position vec4, texCoord vec2, color vec4) vec4 {\r\n\tnormColor := Color / 0xffff\r\n\r\n\tposInUnit := vec2(RectSize.x*texCoord.x, RectSize.y*texCoord.y) + RectPosInUnit\r\n\tif (posInUnit.x >= Thickness) && (posInUnit.x <= TotalSize.x-Thickness) &&\r\n\t\t(posInUnit.y >= Thickness) && (posInUnit.y <= TotalSize.y-Thickness) {\r\n\t\tnormColor.a = 0\r\n\t}\r\n\r\n\tnormColor.rgb *= normColor.a\r\n\treturn normColor\r\n}\r\n")
