// Code generated by file2byteslice. DO NOT EDIT.

package shaders

var Hollow = []byte("// Copyright (c) 2022 Anıl Konaç\n// This file is licensed under the MIT license.\n\n//go:build ignore\n\npackage main\n\nvar Color vec4\nvar RectSize vec2\nvar RectPosInUnit vec2\nvar TotalSize vec2\nvar Thickness float\n\nfunc Fragment(position vec4, texCoord vec2, color vec4) vec4 {\n\tnormColor := Color / 0xffff\n\n\tposInUnit := vec2(RectSize.x*texCoord.x, RectSize.y*texCoord.y) + RectPosInUnit\n\tif (posInUnit.x >= Thickness) && (posInUnit.x <= TotalSize.x-Thickness) &&\n\t\t(posInUnit.y >= Thickness) && (posInUnit.y <= TotalSize.y-Thickness) {\n\t\tnormColor.a = 0\n\t}\n\n\tnormColor.xyz *= normColor.a\n\treturn normColor\n}\n")
