// Code generated by file2byteslice. DO NOT EDIT.

package shaders

var Score = []byte("//go:build ignore\n\npackage main\n\nvar Alpha float\n\nfunc Fragment(position vec4, texCoord vec2, color vec4) vec4 {\n\timgColor := imageSrc0At(texCoord)\n\tnormColor := color / 0xffff\n\tvar normAlpha float\n\tif imgColor == normColor {\n\t\tnormAlpha = 0.0\n\t} else {\n\t\tnormAlpha = Alpha / 0xff\n\t}\n\timgColor.rgb *= normAlpha\n\timgColor.a = normAlpha\n\treturn imgColor\n}\n")
