// Code generated by file2byteslice. DO NOT EDIT.

package shaders

var Score = []byte("//go:build ignore\r\n\r\npackage main\r\n\r\nvar Alpha float\r\n\r\nfunc Fragment(position vec4, texCoord vec2, color vec4) vec4 {\r\n\timgColor := imageSrc0At(texCoord)\r\n\r\n\t// Get font drawing information from red color\r\n\tredIntensity := imgColor.r\r\n\r\n\tfontColor := color\r\n\t// Set alpha of font color to uniform variable\r\n\tfontColor *= Alpha\r\n\r\n\t// Interpolate between the font color and the full transparent color according to the red channel.\r\n\tnewColor := redIntensity*fontColor + (1.0-redIntensity)*vec4(0.0)\r\n\r\n\treturn newColor\r\n}\r\n")
