// Code generated by file2byteslice. DO NOT EDIT.

package shaders

var Title = []byte("//go:build ignore\n\npackage main\n\nvar ShowKeyPrompt float\n\nfunc Fragment(position vec4, texCoord vec2, color vec4) vec4 {\n\talpha := color.a\n\n\tvar imgColor vec4\n\tif ShowKeyPrompt == 1.0 {\n\t\timgColor = imageSrc1UnsafeAt(texCoord)\n\t} else {\n\t\timgColor = imageSrc0UnsafeAt(texCoord)\n\t}\n\timgColor *= alpha\n\n\treturn imgColor\n}\n")
