// Code generated by file2byteslice. DO NOT EDIT.

package shader

var Score = []byte("//go:build ignore\n\npackage main\n\nvar Alpha float\n\nfunc Fragment(position vec4, texCoord vec2, color vec4) vec4 {\n\timgColor := imageSrc0UnsafeAt(texCoord)\n\treturn imgColor.r * color * Alpha\n}\n")
